# Main Test

In [10]:
from model import Model
import numpy as np

## Model Sigmoid

In [19]:
model = Model("model.txt")

In [20]:
print(model)

Berikut merupakan struktur dari model:
Layer 0:
Activation Function: sigmoid
  Perceptron 0:
   Weight 0: -10
   Weight 1: 20
   Weight 2: 20
  Perceptron 1:
   Weight 0: 30
   Weight 1: -20
   Weight 2: -20
Layer 1:
Activation Function: sigmoid
  Perceptron 0:
   Weight 0: -30
   Weight 1: 20
   Weight 2: 20



In [22]:
array_input = [[0],[1]]
model.doffnn(array_input)

array([[0.99995452]])

In [21]:
arr1 = np.array([0,0,1,1])
arr2 = np.array([0,1,0,1])
array_input = np.array([arr1, arr2])
model.doffnn(array_input)

array([[4.54391049e-05, 9.99954520e-01, 9.99954520e-01, 4.54391049e-05]])

## Model Relu Linier

In [23]:
model1 = Model("model_relu.txt")
print(model1)

Berikut merupakan struktur dari model:
Layer 0:
Activation Function: relu
  Perceptron 0:
   Weight 0: 0
   Weight 1: 1
   Weight 2: 1
  Perceptron 1:
   Weight 0: -1
   Weight 1: 1
   Weight 2: 1
Layer 1:
Activation Function: linear
  Perceptron 0:
   Weight 0: 0
   Weight 1: 1
   Weight 2: -2



In [25]:
array_input = [[0],[1]]
model1.doffnn(array_input)

array([[1]])

In [26]:
arr1 = np.array([0,0,1,1])
arr2 = np.array([0,1,0,1])
array_input = np.array([arr1, arr2])
model1.doffnn(array_input)

array([[0, 1, 1, 0]])